# Generated by Django 3.0.3 on 2020-04-07 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mbnjattend', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chgdate', models.DateTimeField(verbose_name='Change Date')),
                ('text', models.CharField(max_length=90, verbose_name='Announcement')),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eval', models.CharField(max_length=90, verbose_name='Exam Name')),
                ('desc', models.CharField(max_length=255, verbose_name='Description')),
                ('subject', models.CharField(blank=True, max_length=90, null=True, verbose_name='Subject')),
                ('score', models.FloatField(blank=True, verbose_name='Score')),
                ('totalscore', models.FloatField(blank=True, verbose_name='Possible Score')),
                ('lettergrade', models.CharField(blank=True, max_length=2, null=True, verbose_name='Letter Grade')),
                ('testdate', models.DateTimeField(verbose_name='Test Date')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Evaluator')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mbnjattend.Course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mbnjattend.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Parental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mbnjattend.Profile')),
            ],
        ),
    ]
