# Generated by Django 3.0.3 on 2020-04-07 15:31

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90, verbose_name='Course Name')),
                ('catnum', models.CharField(blank=True, max_length=90, null=True, verbose_name='Catalog Number')),
                ('desc', models.CharField(blank=True, max_length=255, null=True, verbose_name='Course Description')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90, verbose_name='Grade')),
                ('desc', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usertype', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('committee', 'Committee'), ('head moallim', 'Head Moallim'), ('parent', 'Parent')], max_length=90, verbose_name='Profile Type')),
                ('userid', models.CharField(max_length=90, unique=True, verbose_name='User ID')),
                ('useridtype', models.CharField(choices=[('its', 'ITS'), ('other', 'Other')], max_length=90, verbose_name='ID Type')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('addressln2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address Line 2')),
                ('city', models.CharField(max_length=90, verbose_name='City')),
                ('state', models.CharField(choices=[('de', 'DE'), ('nj', 'NJ'), ('ny', 'NY'), ('pa', 'PA')], max_length=90, verbose_name='State')),
                ('zipcode', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')], verbose_name='Zipcode')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=90, verbose_name='Gender')),
                ('phone', models.CharField(blank=True, max_length=90, null=True, verbose_name='Phone')),
                ('status', models.CharField(max_length=90, verbose_name='Status')),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('rollnbr', models.IntegerField(blank=True, null=True, verbose_name='Roll Number')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Schoolyear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hijriyear', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')], verbose_name='Year Hijri')),
                ('gregyear', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')], verbose_name='Year AD')),
                ('curyear', models.BooleanField(verbose_name='Current Year')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=90, verbose_name='Type')),
                ('transdate', models.DateTimeField(verbose_name='Transaction Date')),
                ('status', models.CharField(blank=True, max_length=90, null=True, verbose_name='Status')),
                ('desc', models.CharField(blank=True, max_length=90, null=True, verbose_name='Description')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Evaluator')),
                ('hijriyear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mbnjattend.Schoolyear', verbose_name='Year Hijri')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mbnjattend.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Madrassah Date')),
                ('schtype', models.CharField(blank=True, choices=[('', '----'), ('ramadan', 'Ramadan'), ('early_dismissal', 'Early dismissal'), ('modified', 'Modified'), ('other', 'Other'), ('cancelled', 'Cancelled'), ('special', 'Special')], max_length=90, null=True, verbose_name='Schedule')),
                ('comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Comments')),
                ('hijriyear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mbnjattend.Schoolyear')),
            ],
        ),
        migrations.CreateModel(
            name='Roster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mbnjattend.Course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mbnjattend.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infotype', models.CharField(max_length=90, verbose_name='Type')),
                ('desc', models.CharField(blank=True, max_length=90, null=True, verbose_name='Description')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mbnjattend.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mbnjattend.Grade'),
        ),
        migrations.AddField(
            model_name='course',
            name='hijriyear',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mbnjattend.Schoolyear', verbose_name='Year Hijri'),
        ),
    ]
